INSERT INTO DESCRIZIONI (ID, COMANDO, STANZA, STATO, PERSONAGGIO, OGGETTO, DESCRIZIONE) VALUES
(1, '0', 'Stanza1', 'true', '0', '0', 'COLONNELLO ROY CAMPBELL: "Snake, il mondo è sull’orlo di una crisi. La Dottoressa Weissmann è stata rapita da BLACK HAND per creare armi autonome. Infiltrati nella loro base, salvala prima che sia troppo tardi. Ogni secondo conta. La missione inizia ora. Buona fortuna."'),
(2, 'Osserva', 'Stanza1', 'true', '0', '0', '"Sei nell’ingresso principale. Luci fioche e telecamere di sicurezza. Sul tavolo, un terminale spento e una passkey brillante. Accanto, un armadietto semiaperto rivela un pezzo di stoffa."'),
(3, 'Osserva', 'Stanza1', 'true', '0', 'Tavolo', 'Il tavolo di metallo ospita una passkey elettronica, che brilla sotto la luce tremolante del terminale spento.'),
(4, 'Prendi', 'Stanza1', 'true', '0', 'Passkey', 'Snake prende la passkey dal tavolo, fredda e solida al tatto.'),
(5, 'Osserva', 'Stanza1', 'true', '0', 'Armadietto', 'L’armadietto è socchiuso, mostrando un’uniforme piegata con cura e un guanto pendente.'),
(6, 'Prendi', 'Stanza1', 'true', '0', 'Uniforme', 'Snake prende l’uniforme da guardia dall’armadietto.'),
(7, 'Usa', 'Stanza1', 'true', '0', 'Uniforme', 'Snake indossa rapidamente l’uniforme, mimetizzandosi.'),
(8, 'Usa', 'Stanza1', 'true', '0','Passkey', 'Snake inserisce la passkey nel pannello, sbloccando la serratura.'),
(9, 'Osserva', 'Stanza2', 'false','0', '0', '"Sei nel cortile: alte mura, fari intermittenti. Due guardie sulla torre e altre pattugliano. La porta del magazzino a ovest è leggermente aperta, mostrando un bagliore interno. Non farti scoprire."'),
(10, 'Usa', 'Stanza2', 'false', '0', 'Uniforme', 'Snake indossa l’uniforme per non destare sospetti nel cortile.'),
(11, 'Usa', 'Stanza2', 'false', '0', 'Pistola', 'Snake stordisce le guardie con rapidi colpi di pistola, lasciandole prive di sensi.'),
(12, 'Osserva', 'Stanza3', 'true', '0', '0', '"Il magazzino è un caos di scaffali, casse e barili. Tra il disordine, spicca una scatola di cartone, apparentemente ordinaria."'),
(13, 'Prendi', 'Stanza3', 'true', '0', 'Scatola', 'Snake esamina e prende la leggera scatola di cartone.'),
(14, 'Osserva', 'Stanza4', 'true', '0', '0', '"Sei nella sala di controllo, il cuore della sicurezza. Grandi schermi mostrano telecamere e dati criptati. Al centro, un terminale principale e un foglietto di carta parzialmente nascosto."'),
(15, 'Osserva', 'Stanza4', 'true', '0', 'Foglietto', 'Il foglietto sgualcito mostra chiaramente il codice: "14112".'),
(16, 'Prendi', 'Stanza4', 'true', '0', 'Foglietto', 'Snake prende il foglietto e lo mette in tasca.'),
(17, 'Osserva', 'Stanza4', 'true', '0', 'Terminale', 'Il terminale risponde. Snake digita rapidamente, selezionando "Disattivazione Telecamere" e confermando.'),
(18, 'Osserva', 'Stanza5', 'true', '0', '0', '"Questo è il corridoio d’accesso. Un ronzio elettronico e rumori di ingranaggi indicano un blocco di sicurezza. Schermi centrali mostrano volti umani indefiniti e pixelati che scorrono."'),
(19, 'Parla', 'Stanza5', 'true', 'IA', 'IA', 'L’immagine si ferma su una figura chiara: "Intruso, accesso bloccato. Dimostra il tuo ingegno per procedere."'),
(20, '0', 'Stanza5', 'Corretto', 'IA', '0', '"Risposta corretta. Accesso al livello intermedio sbloccato."'),
(21, '0', 'Stanza5', 'Sbagliato', 'IA', '0', '"Risposta errata. L’accesso resta bloccato. Riprova."'),
(22, 'Osserva', 'Stanza6', 'false', '0', '0', '“Nell’atrio d’accesso, un gruppo di guardie pattuglia. Il loro badge potrebbe essere utile."'),
(23, 'Usa', 'Stanza6', 'false', '0', 'Pistola', 'Snake usa la pistola stordente, abbattendo rapidamente tutte le guardie.'),
(24, 'Prendi', 'Stanza6', 'true', '0', 'Badge', 'Snake trova un badge di identificazione nella tasca del giubbotto di una guardia.'),
(25, 'Osserva', 'Stanza7', 'true', '0', '0', '“Nell’officina scarsamente illuminata, tra cavi e attrezzi, un vecchio scaffale arrugginito nell’angolo contiene dispositivi inutilizzati."'),
(26, 'Osserva', 'Stanza7', 'true', '0', 'Scaffale', 'Su uno dei ripiani dello scaffale, quasi nascosta, c’è una piccola radio retrò che emette un leggero ronzio.'),
(27, 'Prendi', 'Stanza7', 'true', '0', 'Radio', 'Snake afferra la radio impolverata e ronzante.'),
(28, 'Osserva', 'Stanza8', 'true', '0', '0', '“La sala server è fredda e asettica, illuminata da luci bluastre. Tra i cavi e le ventole dei server, si intravede una piccola chiavetta USB nera opaca con un simbolo criptico."'),
(29, 'Prendi', 'Stanza8', 'true', '0', 'Chiavetta', 'Snake afferra delicatamente la chiavetta USB nera dal suo nascondiglio.'),
(30, 'Usa', 'Stanza8', 'true', '0', 'Radio', 'Snake accende la radio. I LED si illuminano, un ronzio riempie l’aria, e si sintonizza su una frequenza stabile con numeri fissi sul display.'),
(31, 'Osserva', 'Stanza9', 'true', '0', '0', '"La Sala Comunicazioni ha pareti piene di radio. Al centro, un ascensore di vetro bloccato da un pannello di controllo elettronico con simboli e numeri."'),
(32, 'Osserva', 'Stanza9', 'true', '0', 'Pannello', 'Sul pannello, il display mostra: "Inserire la password numerica". I tasti brillano.'),
(33, 'Usa', 'Stanza9', 'true', '0', 'Foglietto', 'Snake inserisce il codice dal foglietto nel pannello. L’ascensore si attiva.'),
(34, 'Osserva', 'Stanza10', 'true', '0', '0', '"Nel laboratorio di ricerca, luci fredde illuminano monitor e schemi. La dottoressa è al centro, fissa su un terminale che monitora tutto."'),
(35, 'Parla', 'Stanza10', 'true', '0', 'Dottoressa', 'La dottoressa: "Snake, non pensavo arrivassi! Ho bisogno di una chiave speciale per bypassare il sistema BLACK HAND. Un dispositivo che acceda al cuore del sistema."'),
(36, 'Dai', 'Stanza10', 'true', '0', 'Chiavetta', 'Snake mostra la chiavetta. La dottoressa si illumina: "Questo potrebbe servire! Dammi un momento per collegarla."'),
(37, 'Osserva', 'Stanza11', 'true', '0', '0', '"Snake, questa stanza è protetta da raggi infrarossi invisibili che si intrecciano. Non letali, ma pericolosi: al contatto, si attiva il gas tossico. È l’ultima stanza prima dell’uscita. Procedi con cautela."'),
(38, 'Usa', 'Stanza11', 'true', '0', 'Sigarette', 'Il fumo delle sigarette rivela i raggi infrarossi. Snake guida la dottoressa attraverso la stanza, raggiungendo il corridoio finale.'),
(39, 'Osserva', 'Stanza12', 'true', '0', '0', '"Il corridoio finale si apre come un lungo tunnel stretto e opprimente.Le pareti, rivestite di metallo scuro, erano attraversate da tubature, cavi scoperti e luci rosse intermittenti."'),
(39, 'Osserva', 'Stanza12', 'true', 'IA', '0', '"IA: Benvenuto, intruso. Sono l’ultimo guardiano. Non c’è via d’uscita senza affrontare la prova finale. Dimostra il tuo valore. Non ti permetterò di vincere facilmente."'),
(40, '0', 'Stanza12', 'Corretto', 'IA', '0', '"IA: Notevole. Hai superato le aspettative... Anomalia! Un programma estraneo sta distruggendo il mio sistema..." L’IA si spegne, il corridoio è true.'),
(41, '0', 'Stanza12', 'Sbagliato', 'IA', '0', '"IA: Errore fatale. Hai fallito. Affronta le conseguenze."'),
(42, 'Osserva', '0', 'true', '0', 'Sigarette', 'Avvertenza: fumare è pericoloso. Le sigarette rivelano la posizione dei sensori a infrarossi (uso limitato).'),
(43, 'Osserva', '0', 'true', '0', 'Pistola', 'Una pistola semiautomatica Beretta 92FS, con silenziatore e munizioni stordenti.'),
(44, 'Osserva', 'Stanza1', 'true', '0', 'Passkey', 'Una chiave elettronica indispensabile per le serrature elettroniche della base.'),
(45, 'Osserva', 'Stanza1', 'true', '0', 'Uniforme', 'Un travestimento completo per Snake, per muoversi inosservato.'),
(46, 'Osserva', 'Stanza3', 'true', '0', 'Scatola', 'Una scatola di cartone. Perfetta per passare inosservato tra le guardie.'),
(47, 'Osserva', 'Stanza6', 'true', '0', 'Badge', 'Un badge di metallo con logo e numero di identificazione della base.'),
(48, 'Osserva', 'Stanza7', 'true', '0', 'Radio', 'Un dispositivo radio retrò in legno, potenzialmente per segnali segreti o funzioni nascoste.'),
(49, 'Osserva', 'Stanza8', 'true', '0', 'Chiavetta', 'La chiavetta contiene il protocollo "Eclipse Omega", un piano segreto per situazioni critiche.');
