CREATE TABLE IF NOT EXISTS DESCRIZIONI (
    ID INT PRIMARY KEY,
    COMANDO VARCHAR(255),
    STANZA VARCHAR(255),
    STATO VARCHAR(255),
    PERSONAGGIO VARCHAR(255),
    OGGETTO VARCHAR(255),
    DESCRIZIONE CLOB(10K)
    );


